### PR TITLE
fix: Check all relevant pre-release versions, not just the latest.

### LINKED ISSUE #334: Consider "too new" prerelease tags when bumping.
This is a follow-up to #322.

In rigetti/quil-rs, we have the following situation:

- Latest stable is `0.14.2`
- Latest prerelease *since* latest stable does not exist.
- *Newest* prerelease before latest stable is `0.14.2-rc.0`
- Before that was `0.10.0-rc.1` (due to previous bug)
- The *largest* prerelease is from even earlier: `0.15.0-rc.0`

We want to avoid the eventual problem of adding a breaking change that would bump us back to `0.15.0-rc.0`. Currently, running the `knope` prerelease flow with `--dry-run` indicates that it would try to bump to this version that already exists.

I think the safest option is for `knope` to bump the latest prerelease if it is newer than the latest stable, *even if* it is newer than the version that the latest stable would bump to. That is, for our situation:

- "Correct" (previous) bump: `0.14.3-rc.0`
- "Fixed" (new) bump: `0.15.0-rc.1`

### PR DESCRIPTION
**Pull request by dbanty**
BREAKING CHANGE: Handling of pre-release versions has been reworked to handle many more edge cases which results in more correct (but different) behavior.

Closes #334

### CODE REVIEW

**Comment by dbanty** [comment]
This replaces #335 — @Shadow53 will you review this please?

File: src/releases/semver/mod.rs [hunk 1]
```diff
@@ -0,0 +1,601 @@
...
+        .transpose()?;
+
+    let mut current_versions = get_current_versions_from_tag(package.name.as_deref())?;
+
+    if let Some(version_from_files) = version_from_files {
+        if version_from_files.pre.is_none() {
+            current_versions.replace_stable_if_newer(version_from_files);
+        } else {
+            current_versions.insert_prerelease(version_from_files);
+        }
```
Comment (Shadow53) [inline src/releases/semver/mod.rs:140]: Why not have a single method that takes a `Version` and updates `CurrentVersions` according to whether the `Version` is a prerelease? (Basically, what if this was moved into a method?)

File: src/releases/semver/version.rs [hunk 2]
```diff
@@ -0,0 +1,140 @@
...
+    pub(crate) pre: Option<Prerelease>,
+}
+
+impl Ord for Version {
+    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
+        self.major
+            .cmp(&other.major)
+            .then(self.minor.cmp(&other.minor))
+            .then(self.patch.cmp(&other.patch))
+            .then({
```
Comment (Shadow53) [inline src/releases/semver/version.rs:22]: Probably not a big performance concern, but consider:

```suggestion
            .then_with(|| self.minor.cmp(&other.minor))
            .then_with(|| self.patch.cmp(&other.patch))
            .then_with(|| {
```

File: src/releases/semver/version.rs [hunk 3]
```diff
@@ -0,0 +1,140 @@
...
+        let version_parts = version
+            .split('.')
+            .map(|part| {
+                part.parse::<u64>()
+                    .map_err(|err| StepError::InvalidSemanticVersion(err.to_string()))
+            })
+            .collect::<Result<Vec<_>, _>>()?;
+        if version_parts.len() != 3 {
+            return Err(StepError::InvalidSemanticVersion(
+                "Version must have 3 parts".to_string(),
```
Comment (Shadow53) [inline src/releases/semver/version.rs:55]: To differentiate from potentially meaning "at least 3"

```suggestion
                "Version must have exactly 3 parts".to_string(),
```

File: src/releases/semver/version.rs [hunk 4]
```diff
@@ -0,0 +1,140 @@
...
+
+#[derive(Clone, Debug, Eq, PartialEq)]
+pub(crate) struct Prerelease {
+    pub(crate) label: Label,
+    pub(crate) version: u64,
+}
+
+impl Display for Prerelease {
+    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
+        write!(f, "{}.{}", self.label, self.version)
```
Comment (Shadow53) [inline src/releases/semver/version.rs:85]: semver.org describes the prerelease section as

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version... Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92, 1.0.0-x-y-z.--.

Not necessarily worth doing anything about for this PR, since `knope` defines the new versions, but potentially worth tracking. The current handling of `Prerelease` only supports a subset of what is allowed by semver.

**Review by Shadow53 — CHANGES_REQUESTED** [review]
Left a variety of comments. Some are things I think should be changed, others are suggestions I'm floating but am okay with having rejected.

File: src/releases/mod.rs [hunk 5]
```diff
@@ -28,27 +30,66 @@ pub(crate) struct Release {
...
+            .and_then(|pres| pres.get(&pre.label));
+        if let Some(recorded_pre) = recorded_pre {
+            if recorded_pre >= &pre {
+                return;
+            }
+        }
+        self.prereleases
+            .entry(stable_component)
+            .or_default()
+            .insert(pre.label.clone(), pre);
```
[the remark this answers is not in the document]
Comment (dbanty) [reply src/releases/mod.rs:75]: We're moving `pre` into the map, so if we don't clone `.label` we can't move `.label` into the map as a key. The only way to avoid clone is with `Rc` I think? Basically, the key of the map _should_ be a reference to part of the type but... that's not easily possible.

File: src/releases/mod.rs [hunk 6]
```diff
@@ -28,27 +30,66 @@ pub(crate) struct Release {
...
+    }
+
+    pub(crate) fn replace_stable_if_newer(&mut self, version: Version) {
+        if let Some(stable) = &self.stable {
+            if stable >= &version {
+                return;
+            }
+        }
+        self.stable = Some(version);
```
[the remark this answers is not in the document]
Comment (dbanty) [reply src/releases/mod.rs:84]: I think I want two types to enforce the invariants since right now there's a bunch of runtime logic which is _hopefully_ correct enforcing that, but not necessarily guaranteed. Rust can do better

File: src/releases/semver/version.rs (hunk 4 above)
Comment (dbanty) [reply src/releases/semver/version.rs:85]: That is why I deleted the semver crate and wrote my own—too much dancing around all of the formats allowed by SemVer to make it more reasonable to deal with. I don't think I want Knope to ever get more flexible (unless someone comes up with a really good reason), but this behavior should be documented...

**Comment by dbanty** [comment]
@Shadow53 I think I fixed all the things, please take another look when you get a chance

**Comment by dbanty** [comment]
Merging this as-is since I think it fixes the bug. We can always improve the code more later!
